# Generated by Django 6.0.3 on 2026-03-22 09:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.CharField(blank=True, max_length=200, verbose_name='SEO')),
                ('phone_numbers', wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, verbose_name='Телефони')),
                ('messenger_links', wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'lable': 'Назва'}), 1: ('wagtail.blocks.URLBlock', (), {'lable': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='URL карти')),
                ('address', wagtail.fields.StreamField([('address', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Адреса'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('address', 1), ('icon', 2)]], {})}, verbose_name='Адреси')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Контактні дані',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_links', wagtail.fields.StreamField([('nav', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Навігаційне меню')),
                ('social_links', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка'}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1), ('URL_link', 2)]], {})}, verbose_name='Соцмережі')),
                ('developer_name', models.CharField(blank=True, max_length=100, verbose_name='Розробник')),
                ('developer_url', models.URLField(blank=True, verbose_name='URL розробника')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='Копірайт')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Налаштування футера',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner_discount', models.CharField(blank=True, max_length=200, verbose_name='Текст банера знижки')),
                ('social_links', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка'}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1), ('URL_link', 2)]], {})}, verbose_name='Соцмережі')),
                ('messenger_links', wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'lable': 'Назва'}), 1: ('wagtail.blocks.URLBlock', (), {'lable': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('button_working_hours', models.CharField(blank=True, max_length=100, verbose_name='Години роботи')),
                ('nav_links', wagtail.fields.StreamField([('nav', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Навігаційне меню')),
                ('cart_icon', models.BooleanField(default=True, verbose_name='Показувати іконку кошика')),
                ('login_url', models.URLField(blank=True, verbose_name='URL входу')),
                ('register_url', models.URLField(blank=True, verbose_name='URL реєстрації')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Налаштування шапки',
            },
        ),
    ]
