# Generated by Django 6.0.3 on 2026-04-09 17:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='messenger_links_en',
            field=wagtail.fields.StreamField([('messenger', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1), ('icon', 2)]], {})}, null=True, verbose_name='Месенджери'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='messenger_links_ru',
            field=wagtail.fields.StreamField([('messenger', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1), ('icon', 2)]], {})}, null=True, verbose_name='Месенджери'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='messenger_links_uk',
            field=wagtail.fields.StreamField([('messenger', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1), ('icon', 2)]], {})}, null=True, verbose_name='Месенджери'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='social_links_en',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, null=True, verbose_name='Соцмережі'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='social_links_ru',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, null=True, verbose_name='Соцмережі'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='social_links_uk',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, null=True, verbose_name='Соцмережі'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='address_en',
            field=wagtail.fields.StreamField([('address', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Адреса'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('address', 1), ('icon', 2)]], {})}, null=True, verbose_name='Адреси'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='address_ru',
            field=wagtail.fields.StreamField([('address', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Адреса'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('address', 1), ('icon', 2)]], {})}, null=True, verbose_name='Адреси'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='address_uk',
            field=wagtail.fields.StreamField([('address', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Адреса'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('address', 1), ('icon', 2)]], {})}, null=True, verbose_name='Адреси'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='email_ru',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='email_uk',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='map_embed_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='URL карти'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='map_embed_url_ru',
            field=models.URLField(blank=True, null=True, verbose_name='URL карти'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='map_embed_url_uk',
            field=models.URLField(blank=True, null=True, verbose_name='URL карти'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='phone_numbers_en',
            field=wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, null=True, verbose_name='Телефони'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='phone_numbers_ru',
            field=wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, null=True, verbose_name='Телефони'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='phone_numbers_uk',
            field=wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, null=True, verbose_name='Телефони'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='seo_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='seo_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='seo_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Копірайт'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Копірайт'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Копірайт'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Розробник'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Розробник'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_name_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Розробник'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='URL розробника'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_url_ru',
            field=models.URLField(blank=True, null=True, verbose_name='URL розробника'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='developer_url_uk',
            field=models.URLField(blank=True, null=True, verbose_name='URL розробника'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_working_hours_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_working_hours_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_working_hours_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Години роботи'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='phone_number_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='phone_number_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='phone_number_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='top_banner_discount_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст банера знижки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='top_banner_discount_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст банера знижки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='top_banner_discount_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст банера знижки'),
        ),
        migrations.AddField(
            model_name='navlinks',
            name='naw_link_en',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AddField(
            model_name='navlinks',
            name='naw_link_ru',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AddField(
            model_name='navlinks',
            name='naw_link_uk',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AddField(
            model_name='statisticsettings',
            name='items_en',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AddField(
            model_name='statisticsettings',
            name='items_ru',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AddField(
            model_name='statisticsettings',
            name='items_uk',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
    ]
