# Generated by Django 6.0.3 on 2026-03-22 11:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='messenger_links',
            field=wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'labl': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('URL_link', 1)]], {})}, verbose_name='Соцмережі'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='messenger_links',
            field=wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'labl': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('URL_link', 1)]], {})}, verbose_name='Соцмережі'),
        ),
    ]
