# Generated by Django 6.0.3 on 2026-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0002_brandsettings_messenger_links_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsettings',
            name='messenger_links_en',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='messenger_links_ru',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='messenger_links_uk',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='social_links_en',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='social_links_ru',
        ),
        migrations.RemoveField(
            model_name='brandsettings',
            name='social_links_uk',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email_uk',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='map_embed_url_en',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='map_embed_url_ru',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='map_embed_url_uk',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_numbers_en',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_numbers_ru',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_numbers_uk',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer_url_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer_url_ru',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='developer_url_uk',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='phone_number_ru',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='phone_number_uk',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='top_banner_discount_en',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='top_banner_discount_ru',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='top_banner_discount_uk',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (Latitude)'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота (Longitude)'),
        ),
    ]
