# Generated by Django 6.0.3 on 2026-03-22 12:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0002_alter_contactsettings_messenger_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='nav_links',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Соцмережі'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='nav_links',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Соцмережі'),
        ),
    ]
