# Generated by Django 6.0.3 on 2026-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0003_alter_footersettings_nav_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='login_url',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='register_url',
        ),
    ]
