# Generated by Django 6.0.3 on 2026-04-11 09:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0003_remove_brandsettings_messenger_links_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='headersettings',
            name='phone_numbers',
            field=wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, verbose_name='Телефони'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='messenger_links',
            field=wagtail.fields.StreamField([('messenger', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Іконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1), ('icon', 2)]], {})}, verbose_name='Месенджери'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (facebook, instagram, youtube)', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Соцмережі'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='phone_numbers',
            field=wagtail.fields.StreamField([('phone', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 1', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Номер 2', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('number_1', 0), ('number_2', 1)]], {})}, verbose_name='Телефони'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='naw_link',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='naw_link_en',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='naw_link_ru',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='navlinks',
            name='naw_link_uk',
            field=wagtail.fields.StreamField([('nav', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('url', 2)]], {})}, null=True, verbose_name='Навігаційне меню'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_en',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_ru',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_uk',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
    ]
