# Generated by Django 6.0.3 on 2026-03-23 12:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0004_remove_headersettings_login_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='messenger_links',
            field=wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='messenger_links',
            field=wagtail.fields.StreamField([('messenger', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Назва (viber, telegram, watsap)'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 1)]], {})}, verbose_name='Месенджери'),
        ),
    ]
