# Generated by Django 6.0.3 on 2026-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0004_remove_headersettings_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='button_working_hours_en',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='button_working_hours_ru',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='button_working_hours_uk',
        ),
    ]
