# Generated by Django 6.0.3 on 2026-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0005_remove_headersettings_button_working_hours_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='text_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='text_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
    ]
