# Generated by Django 6.0.3 on 2026-03-25 10:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0005_alter_contactsettings_messenger_links_and_more'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, verbose_name='Статистика')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Статистика',
            },
        ),
    ]
