# Generated by Django 6.0.3 on 2026-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0006_headersettings_text_headersettings_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='text_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='text_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
    ]
