# Generated by Django 6.0.3 on 2026-04-22 17:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0007_alter_headersettings_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (наприклад: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_en',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (наприклад: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_ru',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (наприклад: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsettings',
            name='items_uk',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (наприклад: 240)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, null=True, verbose_name='Статистика'),
        ),
    ]
