# Generated by Django 6.0.3 on 2026-04-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_cms', '0008_alter_statisticsettings_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navlinks',
            old_name='naw_link',
            new_name='nav_link',
        ),
        migrations.RenameField(
            model_name='navlinks',
            old_name='naw_link_en',
            new_name='nav_link_en',
        ),
        migrations.RenameField(
            model_name='navlinks',
            old_name='naw_link_ru',
            new_name='nav_link_ru',
        ),
        migrations.RenameField(
            model_name='navlinks',
            old_name='naw_link_uk',
            new_name='nav_link_uk',
        ),
    ]
