[project]
name = "nuts"
version = "1.0.0"
description = "корпоративный сайт со встроенным мини магазином"

authors = [
    { name = "Dmitriy", email = "ViatkinDima@gmail.com" }
]

requires-python = ">=3.12,<4.0"

dependencies = [
    "django>=6.0.3,<7.0.0",
    "wagtail>=7.3.1,<8.0.0",
    "django-htmx>=1.27.0,<2.0.0",
    "django-unfold>=0.84.0,<0.85.0",
    "psycopg2-binary>=2.9.11,<3.0.0",
    "pillow>=12.1.1,<13.0.0",
    "whitenoise>=6.12.0,<7.0.0",
    "python-dotenv>=1.2.2,<2.0.0",
    "gunicorn>=25.1.0,<26.0.0",
    "django-environ>=0.13.0,<0.14.0",
    "django-cities-light (>=3.11,<4.0)",
    "celery (>=5.6.2,<6.0.0)",
    "redis (>=7.3.0,<8.0.0)",
    "django-celery-results (>=2.6.0,<3.0.0)",
    "celery-types (>=0.26.0,<0.27.0)",
    "django-vite (>=3.1.0,<4.0.0)",
    "wagtail-localize (>=1.13,<2.0)",
    "django-ninja (>=1.6.2,<2.0.0)",
    "wagtail-ninja (>=0.1.20,<0.2.0)",
    "wagtail-modeltranslation (>=0.16.0,<0.17.0)",
    "wagtailmedia (>=0.17.2,<0.18.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"