# Generated by Django 6.0.3 on 2026-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('mass', models.CharField(blank=True, max_length=50, verbose_name='Маса')),
                ('composition', models.CharField(blank=True, max_length=500, verbose_name='Склад')),
                ('energy_value', models.CharField(blank=True, max_length=100, verbose_name='Енергетична цінність')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Термін придатності')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('articul', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул')),
                ('packaging', models.CharField(choices=[('jar', 'Банка'), ('vacuum', 'Вакуумна'), ('box', 'Коробка')], default='jar', max_length=20, verbose_name='Упаковка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('gallery', models.ManyToManyField(blank=True, to='product_management.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
