# Generated by Django 6.0.3 on 2026-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Акція'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=500, verbose_name='Умови зберігання'),
        ),
    ]
