# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_product_is_sale_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_en',
            field=models.ImageField(null=True, upload_to='gallery/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='gallery/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_uk',
            field=models.ImageField(null=True, upload_to='gallery/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='product',
            name='articul_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='articul_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='articul_uk',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Енергетична цінність'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Енергетична цінність'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Енергетична цінність'),
        ),
        migrations.AddField(
            model_name='product',
            name='mass_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Маса'),
        ),
        migrations.AddField(
            model_name='product',
            name='mass_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Маса'),
        ),
        migrations.AddField(
            model_name='product',
            name='mass_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Маса'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Умови зберігання'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Умови зберігання'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Умови зберігання'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис'),
        ),
    ]
