# Generated by Django 6.0.3 on 2026-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_gallery_image_en_gallery_image_ru_gallery_image_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='FLAVOR_CATEGORIES',
            field=models.CharField(choices=[('jar', 'Банка'), ('vacuum', 'Вакуумна'), ('box', 'Коробка')], default='sweet', max_length=20, verbose_name='Смакові Якості'),
        ),
    ]
