# Generated by Django 6.0.3 on 2026-04-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_product_flavor_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='FLAVOR_CATEGORIES',
            new_name='flavor_categories',
        ),
    ]
