# Generated by Django 6.0.3 on 2026-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_rename_flavor_categories_product_flavor_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='articul_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='articul_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='articul_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_value_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_value_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_value_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mass_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mass_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mass_uk',
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor_categories',
            field=models.CharField(choices=[('sweet', 'Сладкие и десертные'), ('savory', 'Соленые и пикантные'), ('spicy', 'Пряные и необычные')], default='sweet', max_length=20, verbose_name='Смакові Якості'),
        ),
    ]
