# Generated by Django 6.0.3 on 2026-04-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адреса доставки'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='NP City Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='NP відділення'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='NP відділення Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('pending_payment', 'Очікує оплати'), ('cancelled', 'Скасовано')], default='pending_payment', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для доставки'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН)'),
        ),
    ]
