# Generated by Django 6.0.3 on 2026-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_clientorder_delivery_address_clientorder_np_city_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email для доставки'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery',
            field=models.CharField(choices=[('NP', 'Нова пошта'), ('UaP', 'Укрпошта'), ('MP', 'Meest Post'), ('courier', 'Курʼєр'), ('pickup', 'Самовивіз')], default='NP', max_length=20, verbose_name='Доставка'),
        ),
    ]
