# Generated by Django 6.0.3 on 2026-04-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0001_initial'),
        ('order_management', '0003_clientorder_company_clientorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Region', verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery',
            field=models.CharField(choices=[('NP', 'Нова пошта'), ('UaP', 'Укрпошта'), ('MP', 'Meest Post'), ('courier', 'Курʼєр'), ('pickup', 'Самовивіз')], default='NP', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адреса доставки (вулиця, будинок, квартира)'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='np_warehouse_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='NP Відділення'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='NP Відділення Ref'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума замовлення'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ТТН'),
        ),
    ]
