# Generated by Django 6.0.3 on 2026-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_clientorder_city_clientorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='payment_method',
            field=models.CharField(choices=[('liqpay', 'LiqPay / Приват24'), ('cashless', 'Безготівковий розрахунок'), ('cod', 'Накладений платіж (при отриманні)')], default='liqpay', max_length=32, verbose_name='Способ оплати'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery',
            field=models.CharField(choices=[('NP', 'Нова пошта'), ('courier', 'Курʼєр'), ('pickup', 'Самовивіз')], default='NP', max_length=20, verbose_name='Тип доставки'),
        ),
    ]
