# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_clientorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='comment_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='comment_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='company_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компанія'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='company_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компанія'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='company_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компанія'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='delivery_address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адреса доставки (вулиця, будинок, квартира)'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='delivery_address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адреса доставки (вулиця, будинок, квартира)'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='delivery_address_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адреса доставки (вулиця, будинок, квартира)'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='email_en',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='email_ru',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='email_uk',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_city_ref_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP City Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_city_ref_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP City Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_city_ref_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP City Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NP Відділення'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NP Відділення'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_description_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NP Відділення'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_ref_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP Відділення Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_ref_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP Відділення Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='np_warehouse_ref_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NP Відділення Ref'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='phone_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='phone_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='phone_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='recipient_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='recipient_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='recipient_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='tracking_number_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТТН'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='tracking_number_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТТН'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='tracking_number_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТТН'),
        ),
    ]
