# Generated by Django 6.0.3 on 2026-04-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_delivery_method_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.deliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
