# Generated by Django 6.0.3 on 2026-03-25 13:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailNewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_page', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})})),
            ],
            options={
                'verbose_name': 'Новина',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_banner', wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, verbose_name='Банер')),
                ('images', wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Галерея',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_page', wagtail.fields.RichTextField(blank=True)),
                ('subtitle', wagtail.fields.RichTextField(blank=True)),
                ('promo_banner', wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})})),
            ],
            options={
                'verbose_name': 'Сторінка новин',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Page404',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image', models.ImageField(blank=True, null=True, upload_to='404/')),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': '404 сторінка',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('video_banner_url', models.URLField(blank=True)),
                ('video_banner_title', models.CharField(blank=True, max_length=255)),
                ('video_banner_text', models.CharField(blank=True, max_length=255)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_text', wagtail.fields.RichTextField(blank=True)),
                ('about_button_text', models.CharField(blank=True, max_length=100)),
                ('about_button_url', models.URLField(blank=True)),
                ('about_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})})),
                ('promo_video_url', models.URLField(blank=True)),
                ('promo_video_title', models.CharField(blank=True, max_length=255)),
                ('promo_video_text', models.CharField(blank=True, max_length=255)),
                ('benefit_title', models.CharField(blank=True, max_length=255)),
                ('benefit_subtitle', models.CharField(blank=True, max_length=255)),
                ('benefit_items', wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})})),
                ('eco_title', models.CharField(blank=True, max_length=255)),
                ('eco_text', models.CharField(blank=True, max_length=255)),
                ('eco_url', models.URLField(blank=True)),
                ('news_title', models.CharField(blank=True, max_length=255)),
                ('news_subtitle', models.CharField(blank=True, max_length=255)),
                ('video_banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
            },
            bases=('wagtailcore.page',),
        ),
    ]
