# Generated by Django 6.0.3 on 2026-03-26 12:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0001_initial'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutManufacturerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('gallery_section_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секции галереи')),
                ('news_section_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секции новостей')),
                ('news_section_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок секции новостей')),
                ('content', wagtail.fields.StreamField([('content', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2)]], {})}, verbose_name='Контент')),
                ('top_baner', wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Видео баннер')),
                ('statistic', wagtail.fields.StreamField([('statistic', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Число (например: 240)'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Одиниця (Га, %, шт)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Опис'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Підопис', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('unit', 1), ('description', 2), ('sub_description', 3)]], {})}, verbose_name='Статистика')),
                ('image_baner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением')),
            ],
            options={
                'verbose_name': 'Страница о производителе',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_image',
        ),
    ]
