# Generated by Django 6.0.3 on 2026-03-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0002_page404'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page404',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='page404',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
