# Generated by Django 6.0.3 on 2026-03-28 17:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0002_aboutmanufacturerpage_remove_main_video_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmanufacturerpage',
            name='statistic',
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='content',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент'),
        ),
    ]
