# Generated by Django 6.0.3 on 2026-03-28 17:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0003_remove_aboutmanufacturerpage_statistic_and_more'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClientsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст страницы')),
                ('image_top_banner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением')),
                ('content_block', wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы')),
                ('image_footer_banner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением в футере')),
            ],
            options={
                'verbose_name': 'Страница для корпоративных клиентов',
                'verbose_name_plural': 'Страницы для корпоративных клиентов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('thanks_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секции благодарности')),
                ('banner_title', models.CharField(blank=True, max_length=255, verbose_name='Текст секции благодарности')),
                ('image_banner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением')),
            ],
            options={
                'verbose_name': 'Страница благодарности за заказ',
                'verbose_name_plural': 'Страницы благодарности за заказ',
            },
            bases=('wagtailcore.page',),
        ),
    ]
