# Generated by Django 6.0.3 on 2026-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0003_page404_image_page404_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page404',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='404/'),
        ),
    ]
