# Generated by Django 6.0.3 on 2026-03-28 18:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0004_corporateclientspage_orderplaced'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPaymentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image_top_banner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением вверху страницы')),
                ('content_block', wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы')),
                ('video_footer_banner', wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Баннер с изображением в футере')),
            ],
            options={
                'verbose_name': 'Страница "Доставка и оплата"',
                'verbose_name_plural': 'Страница "Доставка и оплата"',
            },
            bases=('wagtailcore.page',),
        ),
    ]
