# Generated by Django 6.0.3 on 2026-03-25 09:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0005_newslistpage_detailnewspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailnewspage',
            options={'verbose_name': 'Новина'},
        ),
        migrations.RemoveField(
            model_name='detailnewspage',
            name='image',
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}),
        ),
    ]
