# Generated by Django 6.0.3 on 2026-03-30 10:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0005_deliverypaymentpage'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image_top_baner', wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением вверху страницы')),
                ('content_block', wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
