# Generated by Django 6.0.3 on 2026-03-25 09:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0006_alter_detailnewspage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailnewspage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='detailnewspage',
            name='text',
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}),
        ),
        migrations.AlterField(
            model_name='detailnewspage',
            name='title_page',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
