# Generated by Django 6.0.3 on 2026-04-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0006_catalogproduct_useragreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogproduct',
            options={'verbose_name': 'Страница каталог продукции', 'verbose_name_plural': 'Страницы каталог продукции'},
        ),
        migrations.AlterModelOptions(
            name='useragreement',
            options={'verbose_name': 'Страница пользовательское соглашение'},
        ),
    ]
