# Generated by Django 6.0.3 on 2026-03-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0007_remove_detailnewspage_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslistpage',
            options={'verbose_name': 'Сторінка новин'},
        ),
    ]
