# Generated by Django 6.0.3 on 2026-04-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0008_addresspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresspage',
            options={'verbose_name': 'Сторінка адреси'},
        ),
    ]
