# Generated by Django 6.0.3 on 2026-04-09 17:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0009_alter_addresspage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='content_en',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='content_ru',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='content_uk',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='gallery_section_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции галереи'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='gallery_section_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции галереи'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='gallery_section_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции галереи'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='image_baner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='image_baner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='image_baner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='news_section_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции новостей'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='top_baner_en',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='top_baner_ru',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AddField(
            model_name='aboutmanufacturerpage',
            name='top_baner_uk',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='image_top_baner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='image_top_baner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='image_top_baner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='body_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='body_text_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='body_text_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текст страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_footer_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_footer_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_footer_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_top_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_top_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='corporateclientspage',
            name='image_top_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='image_top_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='image_top_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='image_top_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_en',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_ru',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_uk',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='body_en',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='body_ru',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='body_uk',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='title_page_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='title_page_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailnewspage',
            name='title_page_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='images_en',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='images_ru',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='images_uk',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_url_ru',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_button_url_uk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_images_en',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_images_ru',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_images_uk',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_text_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_text_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='about_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_items_en',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_items_ru',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_items_uk',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='benefit_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_url_ru',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='eco_url_uk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='news_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_url_ru',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='promo_video_url_uk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_url_ru',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='video_banner_url_uk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='promo_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='promo_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='promo_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='subtitle_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='subtitle_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='subtitle_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='title_page_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='title_page_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='title_page_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='banner_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст секции благодарности'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='banner_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст секции благодарности'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='banner_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст секции благодарности'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='image_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='image_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='image_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='thanks_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции благодарности'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='thanks_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции благодарности'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='thanks_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции благодарности'),
        ),
        migrations.AddField(
            model_name='page404',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page404',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page404',
            name='text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='text_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='text_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
