# Generated by Django 6.0.3 on 2026-04-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0010_aboutmanufacturerpage_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='eco_url_en',
        ),
        migrations.RemoveField(
            model_name='main',
            name='eco_url_ru',
        ),
        migrations.RemoveField(
            model_name='main',
            name='eco_url_uk',
        ),
        migrations.RemoveField(
            model_name='main',
            name='promo_video_url_en',
        ),
        migrations.RemoveField(
            model_name='main',
            name='promo_video_url_ru',
        ),
        migrations.RemoveField(
            model_name='main',
            name='promo_video_url_uk',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_url_en',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_url_ru',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_url_uk',
        ),
    ]
