# Generated by Django 6.0.3 on 2026-04-11 09:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0011_remove_main_eco_url_en_remove_main_eco_url_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='content',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='content_en',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='content_ru',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='content_uk',
            field=wagtail.fields.StreamField([('content', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='image_baner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='image_baner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='image_baner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='image_baner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_en',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_ru',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_uk',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='content_block',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='image_top_baner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='image_top_baner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='image_top_baner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='image_top_baner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='content_block',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_footer_banner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_footer_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_footer_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_footer_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_top_banner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_top_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_top_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='corporateclientspage',
            name='image_top_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='content_block',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='content_block_en',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='content_block_ru',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='content_block_uk',
            field=wagtail.fields.StreamField([('content_block', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('body_text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='image_top_banner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='image_top_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='image_top_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='image_top_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением вверху страницы'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_en',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_ru',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_uk',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_en',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_ru',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_uk',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='main',
            name='benefit_items',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='main',
            name='benefit_items_en',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='benefit_items_ru',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='benefit_items_uk',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': 'Посилання на відео', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='image_banner',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='image_banner_en',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='image_banner_ru',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='image_banner_uk',
            field=wagtail.fields.StreamField([('image_baner', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение баннера', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 500, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'URL кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('button_text', 3), ('button_url', 4)]], {})}, null=True, verbose_name='Баннер с изображением'),
        ),
    ]
