# Generated by Django 6.0.3 on 2026-04-22 11:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0012_alter_aboutmanufacturerpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_en',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_ru',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='aboutmanufacturerpage',
            name='top_baner_uk',
            field=wagtail.fields.StreamField([('top_baner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Видео баннер'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_en',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_ru',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='deliverypaymentpage',
            name='video_footer_banner_uk',
            field=wagtail.fields.StreamField([('image_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Баннер с изображением в футере'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_en',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_ru',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_uk',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='promo_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True),
        ),
    ]
