# Generated by Django 6.0.3 on 2026-04-22 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0013_alter_aboutmanufacturerpage_top_baner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='video_banner_text',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_text_en',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_text_ru',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_text_uk',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_title',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_title_en',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_title_ru',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_title_uk',
        ),
        migrations.RemoveField(
            model_name='main',
            name='video_banner_url',
        ),
        migrations.AddField(
            model_name='main',
            name='top_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='main',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='main',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='main',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
    ]
