# Generated by Django 6.0.3 on 2026-04-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0014_remove_main_video_banner_text_and_more'),
        ('wagtailimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspage',
            name='image_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення на сторінці'),
        ),
        migrations.AddField(
            model_name='addresspage',
            name='image_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення на сторінці'),
        ),
        migrations.AddField(
            model_name='addresspage',
            name='image_uk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Зображення на сторінці'),
        ),
    ]
