# Generated by Django 6.0.3 on 2026-04-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0015_addresspage_image_en_addresspage_image_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresspage',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='addresspage',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='addresspage',
            name='image_uk',
        ),
    ]
