# Generated by Django 6.0.3 on 2026-04-22 17:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0016_remove_addresspage_image_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Головна сторінка'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_text_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_url_ru',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_button_url_uk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_images_en',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_images_ru',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_images_uk',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_items',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_items_en',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_items_ru',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_items_uk',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фонове зображення', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Клас іконки (наприклад: icons-group4)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 1'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Текст 2'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('icon', 1), ('title', 2), ('text_1', 3), ('text_2', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_subtitle_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_text_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, default=list, null=True, verbose_name='Банер'),
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
