# Generated by Django 6.0.3 on 2026-04-22 17:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0017_alter_homepage_options_homepage_about_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='images',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video_file', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_en',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video_file', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_ru',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video_file', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='images_uk',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення', 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('video_file', 1)]], {'label': 'Вміст (Картинка або Відео)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Опис', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('large', 'Великий (7/12)'), ('medium', 'Середній (5/12)'), ('full', 'На всю ширину з відео'), ('small', 'Маленький (4/12)')], 'label': 'Розмір'}), 6: ('wagtail.blocks.StructBlock', [[('media', 2), ('title', 3), ('description', 4), ('size', 5)]], {})}, null=True, verbose_name='Галерея'),
        ),
    ]
