# Generated by Django 6.0.3 on 2026-04-22 18:21

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0018_alter_gallerypage_images_alter_gallerypage_images_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_button_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_button_url_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_button_url_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_button_url_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_text_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_text_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_text_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_title_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_title_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='eco_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_text_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_text_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_text_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_title_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_title_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_video_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_banner_section',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Еко банер секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_banner_section_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Еко банер секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_banner_section_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Еко банер секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='eco_banner_section_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Еко банер секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_section',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Промо відео секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_section_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Промо відео секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_section_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Промо відео секція'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_video_section_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Промо відео секція'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_button_text',
            field=models.CharField(blank=True, default='Читати більше', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_button_text_en',
            field=models.CharField(blank=True, default='Читати більше', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_button_text_ru',
            field=models.CharField(blank=True, default='Читати більше', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_button_text_uk',
            field=models.CharField(blank=True, default='Читати більше', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Короткий опис для головної'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Короткий опис для головної'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text_ru',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Короткий опис для головної'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text_uk',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Короткий опис для головної'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (якщо пустий - візьме зі сторінки)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (якщо пустий - візьме зі сторінки)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (якщо пустий - візьме зі сторінки)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (якщо пустий - візьме зі сторінки)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_banner',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, verbose_name='Топ банер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_banner_en',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Топ банер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_banner_ru',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Топ банер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_banner_uk',
            field=wagtail.fields.StreamField([('video_banner', 3)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Відео файл (MP4)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 255}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul'], 'help_text': 'Додайте опис для банера', 'label': 'Текст'}), 3: ('wagtail.blocks.StructBlock', [[('video_file', 0), ('title', 1), ('text', 2)]], {})}, null=True, verbose_name='Топ банер'),
        ),
    ]
