# Generated by Django 6.0.3 on 2026-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_user_managers_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_jur_person',
            field=models.BooleanField(default=False, verbose_name='Юридична особа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_fop',
            field=models.BooleanField(default=False, verbose_name='ФОП'),
        ),
    ]
