# Generated by Django 6.0.3 on 2026-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_user_is_jur_person_alter_user_is_fop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По батькові'),
        ),
    ]
