# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_user_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='address',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='address',
            name='company_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='address',
            name='company_name_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_en',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_ru',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_uk',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По батькові'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По батькові'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='По батькові'),
        ),
    ]
