# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key_en',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ сесії'),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key_ru',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ сесії'),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key_uk',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ сесії'),
        ),
    ]
