# Generated by Django 6.0.3 on 2026-04-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_session_key_en_cart_session_key_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key_en',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key_ru',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key_uk',
        ),
    ]
